export default {
  "04bfa6d0": [() => import(/* webpackChunkName: "04bfa6d0" */ "@site/docs/module1/index.mdx"), "@site/docs/module1/index.mdx", require.resolveWeak("@site/docs/module1/index.mdx")],
  "17896441": [() => import(/* webpackChunkName: "17896441" */ "@theme/DocItem"), "@theme/DocItem", require.resolveWeak("@theme/DocItem")],
  "18891827": [() => import(/* webpackChunkName: "18891827" */ "@site/docs/overview.mdx"), "@site/docs/overview.mdx", require.resolveWeak("@site/docs/overview.mdx")],
  "1a4e3797": [() => import(/* webpackChunkName: "1a4e3797" */ "@theme/SearchPage"), "@theme/SearchPage", require.resolveWeak("@theme/SearchPage")],
  "2e9d9707": [() => import(/* webpackChunkName: "2e9d9707" */ "@site/docs/module3/index.mdx"), "@site/docs/module3/index.mdx", require.resolveWeak("@site/docs/module3/index.mdx")],
  "404b5d86": [() => import(/* webpackChunkName: "404b5d86" */ "@generated/docusaurus-plugin-content-docs/default/p/textbook-fr-docs-d42.json"), "@generated/docusaurus-plugin-content-docs/default/p/textbook-fr-docs-d42.json", require.resolveWeak("@generated/docusaurus-plugin-content-docs/default/p/textbook-fr-docs-d42.json")],
  "5e95c892": [() => import(/* webpackChunkName: "5e95c892" */ "@theme/DocsRoot"), "@theme/DocsRoot", require.resolveWeak("@theme/DocsRoot")],
  "5e9f5e1a": [() => import(/* webpackChunkName: "5e9f5e1a" */ "@generated/docusaurus.config"), "@generated/docusaurus.config", require.resolveWeak("@generated/docusaurus.config")],
  "9b8695b8": [() => import(/* webpackChunkName: "9b8695b8" */ "@site/docs/module4/index.mdx"), "@site/docs/module4/index.mdx", require.resolveWeak("@site/docs/module4/index.mdx")],
  "a7456010": [() => import(/* webpackChunkName: "a7456010" */ "@generated/docusaurus-plugin-content-pages/default/__plugin.json"), "@generated/docusaurus-plugin-content-pages/default/__plugin.json", require.resolveWeak("@generated/docusaurus-plugin-content-pages/default/__plugin.json")],
  "a7bd4aaa": [() => import(/* webpackChunkName: "a7bd4aaa" */ "@theme/DocVersionRoot"), "@theme/DocVersionRoot", require.resolveWeak("@theme/DocVersionRoot")],
  "a94703ab": [() => import(/* webpackChunkName: "a94703ab" */ "@theme/DocRoot"), "@theme/DocRoot", require.resolveWeak("@theme/DocRoot")],
  "aba21aa0": [() => import(/* webpackChunkName: "aba21aa0" */ "@generated/docusaurus-plugin-content-docs/default/__plugin.json"), "@generated/docusaurus-plugin-content-docs/default/__plugin.json", require.resolveWeak("@generated/docusaurus-plugin-content-docs/default/__plugin.json")],
  "c141421f": [() => import(/* webpackChunkName: "c141421f" */ "@generated/docusaurus-theme-search-algolia/default/__plugin.json"), "@generated/docusaurus-theme-search-algolia/default/__plugin.json", require.resolveWeak("@generated/docusaurus-theme-search-algolia/default/__plugin.json")],
  "c4f5d8e4": [() => import(/* webpackChunkName: "c4f5d8e4" */ "@site/src/pages/index.js"), "@site/src/pages/index.js", require.resolveWeak("@site/src/pages/index.js")],
  "d2e43329": [() => import(/* webpackChunkName: "d2e43329" */ "@site/docs/module2/index.mdx"), "@site/docs/module2/index.mdx", require.resolveWeak("@site/docs/module2/index.mdx")],
  "f8409a7e": [() => import(/* webpackChunkName: "f8409a7e" */ "@site/docs/intro.mdx"), "@site/docs/intro.mdx", require.resolveWeak("@site/docs/intro.mdx")],};
